#!/bin/bash

########################################################


# Peduncle extraction: following processing in SUIT
# File(s) stored as iw_SUIT_1mm*.nii
# Labels are 3 (rMCP), 4 (lMCP), 5 (rICP), 6 (lICP)


########################################################

direc=~/Desktop/CervicalDystonia/SUIT_cereb

for dir in $(ls $direc); do

	file=${dir}/iw_SUIT_1mm*.nii

	fslmaths ${file} ${dir}/mask_no_nan.nii

	fslmaths ${direc}/${dir}/mask_no_nan.nii -thr 3 -uthr 3 -bin ${direc}/${dir}/tmp3.nii
	fslmaths ${direc}/${dir}/mask_no_nan.nii -thr 4 -uthr 4 -bin ${direc}/${dir}/tmp4.nii
	fslmaths ${direc}/${dir}/mask_no_nan.nii -thr 5 -uthr 5 -bin ${direc}/${dir}/tmp5.nii
	fslmaths ${direc}/${dir}/mask_no_nan.nii -thr 6 -uthr 6 -bin ${direc}/${dir}/tmp6.nii

	rMCP=$(fslstats ${direc}/${dir}/tmp3.nii -V | awk '{print $1}')
	lMCP=$(fslstats ${direc}/${dir}/tmp4.nii -V | awk '{print $1}')
	rICP=$(fslstats ${direc}/${dir}/tmp5.nii -V | awk '{print $1}')
	lICP=$(fslstats ${direc}/${dir}/tmp6.nii -V | awk '{print $1}')

	echo "$rMCP\n$lMCP\n$rICP\n$lICP" >> ${direc}/${dir}/peduncles.txt

	rm ${direc}/${dir}/tmp*

done
